// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOf26BDViqSuZd6QsMT07g1jx_wY8llk4',
    appId: '1:722307145033:web:2fe7ad2b6c08792d77ce98',
    messagingSenderId: '722307145033',
    projectId: 'turf-patrol-f3d51',
    authDomain: 'turf-patrol-f3d51.firebaseapp.com',
    storageBucket: 'turf-patrol-f3d51.appspot.com',
    measurementId: 'G-7BL3DB5M53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3O4iuRL8SCDh-4ALNkIeZTYWo1jb13CI',
    appId: '1:722307145033:android:df18c4d1d482748377ce98',
    messagingSenderId: '722307145033',
    projectId: 'turf-patrol-f3d51',
    storageBucket: 'turf-patrol-f3d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4xq3OOtvQRK3c0SKGCSHzJK1bXc8PziI',
    appId: '1:722307145033:ios:c4263b8fdc74085b77ce98',
    messagingSenderId: '722307145033',
    projectId: 'turf-patrol-f3d51',
    storageBucket: 'turf-patrol-f3d51.appspot.com',
    iosBundleId: 'com.example.turfPatrol',
  );
}
