// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgkOTw5j06v8VkxKzgQ8K9d3kwle4YBY',
    appId: '1:512605274541:web:87b2335fced8a9e958a124',
    messagingSenderId: '512605274541',
    projectId: 'turf-patrol2',
    authDomain: 'turf-patrol2.firebaseapp.com',
    storageBucket: 'turf-patrol2.appspot.com',
    measurementId: 'G-2EZZV8NK81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8kJ11v3GtI0fsUBgcAnBju-Q84oBM3c',
    appId: '1:512605274541:android:edb888e5fc47e40f58a124',
    messagingSenderId: '512605274541',
    projectId: 'turf-patrol2',
    storageBucket: 'turf-patrol2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7e6I_rGKKM0TWtzlsV2YfwfgI7a6WRc',
    appId: '1:512605274541:ios:974e8ae3f74aa94058a124',
    messagingSenderId: '512605274541',
    projectId: 'turf-patrol2',
    storageBucket: 'turf-patrol2.appspot.com',
    iosBundleId: 'com.example.turfPatrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7e6I_rGKKM0TWtzlsV2YfwfgI7a6WRc',
    appId: '1:512605274541:ios:974e8ae3f74aa94058a124',
    messagingSenderId: '512605274541',
    projectId: 'turf-patrol2',
    storageBucket: 'turf-patrol2.appspot.com',
    iosBundleId: 'com.example.turfPatrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgkOTw5j06v8VkxKzgQ8K9d3kwle4YBY',
    appId: '1:512605274541:web:abd81953901d2e1958a124',
    messagingSenderId: '512605274541',
    projectId: 'turf-patrol2',
    authDomain: 'turf-patrol2.firebaseapp.com',
    storageBucket: 'turf-patrol2.appspot.com',
    measurementId: 'G-CV9ELJQTJ4',
  );

}